FirstMVCApp/Models/DogViewModel.cs
namespace FirstMVCApp.Models
{
    public class DogViewModel
    {
        public string Name { get; set; } // Setup the model structure that will be used in the controller

        public string Description { get; set; }

        public int Age { get; set; }
    }
}

FirstMVCApp/Models/ErrorViewModel.cs
namespace FirstMVCApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FirstMVCApp/Controllers/DogAppController.cs
using Microsoft.AspNetCore.Mvc;
using FirstMVCApp.Models; // Add the models to this controller

namespace FirstMVCApp.Controllers
{
    public class DogAppController : Controller // will link to the view that says DogApp
    {
        // Use static so that after page is redirected to index, list will not be empty
        private static List<DogViewModel> dogs = new List<DogViewModel>();  // List<T> demonstrates a list of objects

        public IActionResult Index() // looks for method name inside of linked view
        {

            // DogViewModel and its information is being passed to the "Index" View, to decide how it will be presented 
            return View(dogs);
        }

        public IActionResult Create() // This will return the view with the form
        {
         
            DogViewModel dogVm = new DogViewModel(); // when Create tab is clicked, none of the information will be filled out, creates a new object each time

            return View(dogVm); // return the view with the new dog information
        }

        // The information from the form will automatically get created as a new object 
        public IActionResult CreateDog(DogViewModel newDog) // When user clicks "add" on form this interface will be called
        {
            // return View("Index"); 
            dogs.Add(newDog);  // After user has entered dog object, add it to the list

            // the previous return will not work because the DogViewModel will have no information, so the fields in the view will be null
            // RedirectToAction returns the action listed as "Index" instead with all the information so the fields will not be empty
            return RedirectToAction(nameof(Index)); 
        }
    }
}

FirstMVCApp/Controllers/HomeController.cs
using FirstMVCApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstMVCApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger; // makes the logs that will be produced read_only

        public HomeController(ILogger<HomeController> logger) // logs information
        {
            _logger = logger;
        }

        public IActionResult Index() // sends to home page that is located in View()
        {
            return View();
        }

        public IActionResult Privacy() // sends to privacy page that is located in View()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() // takes care of what happens when error occurs
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FirstMVCApp/Views/DogApp/Create.cshtml
@model FirstMVCApp.Models.DogViewModel

@*
    Linking the controller data to the view is called DATA BINDING
*@

<h1>Create</h1>

<hr />

<div class="row">
    <div class="col-6"> <!-- Ctrl + K + D to format HTML indentations-->

        <div class="card"> <!--Card formatting style, makes all this info format into a card-->
            <div class="card-header">
                <h5>Add Dog</h5>
                <hr />
                <div class="card-body">
                    <!--form needs to be linked to correct endpoint so that data can be recieved-->
                    <form asp-controller="DogApp" asp-action="CreateDog" method="post"> <!--asp controller defines the controller that is being used, asp action defines the action that the form is linked to, method defines whether the form post(create) or get(read)

                        <!--Creating a form that will be sent to the dog list-->
                        <div class="mb-3">
                            <label class="form-label">Dog Name</label>
                            <input asp-for=Name type="text" class="form-control " /> <!--asp-for sets which property will be linked to which input-->
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Description</label>
                            <input asp-for=Description type="text" class="form-control" />
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Age</label>
                            <input asp-for=Age type="number" class="form-control" />
                        </div>
                       
                        <div class="mb-3"> <!--mb-3 adds spaces between each div-->
                            <button class="btn btn-primary" type="submit">Add</button> <!--class will format the look of the button and set it to primary color--><!--button of type submit, will submit a form-->
                        </div>
                    </form>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

FirstMVCApp/Views/DogApp/Index.cshtml
@*
    Model and Information has been passed from Controller->
    Now the type of object that the View expects to be passed to it is the from the DogViewModel->
*@
@*
    the @-Model becomes an object that now can be used to display the fields
*@


@*
    Since a List is being used, set the model to a list and create a for loop to show all the information
*@

@model List<FirstMVCApp.Models.DogViewModel> // @ sign tells compiler it is C# and not HTML



<h1>Dogs</h1>

<ul>
    @foreach(var dog in Model)  // Model is now the list, so it can be looped through
    {
        <li>@dog.Name:
        <ul>
            <li>Description: @dog.Description</li> <!--at(Model) grabbing information from controller and using it here-->
            <li>Age: @dog.Age</li>
        </ul>
    

    </li>
    }
</ul>

FirstMVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>Currently in the process of learning C# with ASP.NET!</p>

</div>

FirstMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="DogApp" asp-action="Index">DogApp🐶</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DogApp" asp-action="Index">Dog List📃</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DogApp" asp-action="Create">Create➕</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FirstMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
 a:hover{
     background-color: cornflowerblue;
 }
</style>